# Generated by Django 4.2.6 on 2025-02-21 19:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Pago',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('monto', models.DecimalField(decimal_places=2, max_digits=10)),
                ('metodo_pago', models.CharField(max_length=100)),
                ('codigo_pago', models.CharField(max_length=100)),
                ('qr_codigo', models.ImageField(upload_to='qr_codes/')),
                ('comprobante_pago', models.FileField(blank=True, null=True, upload_to='comprobantes/')),
            ],
        ),
        migrations.CreateModel(
            name='Pedido',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('estado', models.IntegerField(choices=[(1, 'Pendiente'), (2, 'Completado'), (3, 'Cancelado')], default=1)),
            ],
        ),
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('descripcion', models.TextField()),
                ('precio', models.IntegerField()),
                ('foto', models.ImageField(upload_to='productos/')),
                ('kg', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('direccion', models.CharField(max_length=200)),
                ('password', models.CharField(max_length=100)),
                ('rol', models.IntegerField(choices=[(1, 'Administrador'), (2, 'Vendedor'), (3, 'Cliente')], default=3)),
                ('estado', models.IntegerField(choices=[(1, 'Activo'), (2, 'Bloqueado')], default=1)),
                ('foto', models.ImageField(blank=True, default='usuarios/default.png', null=True, upload_to='usuarios/')),
                ('token_recuperar', models.CharField(blank=True, default='', max_length=254, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='PedidoItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.PositiveIntegerField(default=1)),
                ('pedido', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items_pedido', to='concentrado_equino.pedido')),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='concentrado_equino.producto')),
            ],
        ),
        migrations.AddField(
            model_name='pedido',
            name='items',
            field=models.ManyToManyField(through='concentrado_equino.PedidoItem', to='concentrado_equino.producto'),
        ),
        migrations.AddField(
            model_name='pedido',
            name='usuario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='concentrado_equino.usuario'),
        ),
    ]
