# Generated by Django 4.2.6 on 2025-01-08 18:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('concentrado_equino', '0002_alter_usuario_foto'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='foto',
            field=models.ImageField(blank=True, default='usuarios/default.png', null=True, upload_to='usuarios/'),
        ),
    ]
