# Generated by Django 4.2.6 on 2025-03-03 19:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('concentrado_equino', '0002_alter_carritoitem_cantidad'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pago',
            name='qr_codigo',
            field=models.ImageField(blank=True, null=True, upload_to='qr_codes/'),
        ),
    ]
