# Generated by Django 4.2.6 on 2025-01-30 17:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('concentrado_equino', '0004_alter_producto_precio'),
    ]

    operations = [
        migrations.AlterField(
            model_name='producto',
            name='kg',
            field=models.IntegerField(),
        ),
    ]
