# Generated by Django 4.2.6 on 2025-02-14 17:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('concentrado_equino', '0005_alter_producto_kg'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='rol',
            field=models.IntegerField(choices=[(1, 'Administrador'), (2, 'Vendedor'), (3, 'Cliente')], default=3),
        ),
    ]
